[phases.install]
cmds = ['npm install --include=dev']

[phases.build]
cmds = [
  'npx prisma generate --schema=prisma/schema.prisma',
  'npm run build'
]

[start]
cmd = 'npx prisma migrate deploy --schema=prisma/schema.prisma && node dist/index.js'
